### ISSUE TITLE
Failed to activate the toggle-invisibles package

### ISSUE THREAD

**Issue by csnover** [lee-dohm/toggle-invisibles#3]
[Enter steps to reproduce below:]

1. Update Atom to 0.194.0
2. Start Atom

**Atom Version**: 0.194.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.9.5
**Thrown From**: [toggle-invisibles](https://github.com/lee-dohm/toggle-invisibles) package, v0.1.0

### Stack Trace

Failed to activate the toggle-invisibles package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (~/.atom/packages/toggle-invisibles/lib/toggle-invisibles.coffee:24:25)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:222:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:203:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:195:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:418:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:413:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:394:46)
```

### Installed Packages

```coffee
# User
toggle-invisibles, v0.1.0

# Dev
No dev packages
```

**Comment by benadamstyles** [comment]
:+1: Same/similar error now too:

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: [toggle-invisibles](https://github.com/lee-dohm/toggle-invisibles) package, v0.1.0

### Stack Trace

Failed to activate the toggle-invisibles package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/Users/ben/Dropbox/Software/.atom/packages/toggle-invisibles/lib/toggle-invisibles.coffee:22:23)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:232:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:212:32
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:205:26
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:201:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:474:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:457:29
  at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:300:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:19)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:436:46)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:625:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:79:25)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:35:9)

```

### Commands

```
```

### Config

``` json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "remember-session",
      "ask-stack",
      "symbols-view",
      "language-sweetjs",
      "atom-beautify"
    ],
    "themes": [
      "seti-ui",
      "kingfisher-syntax"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

``` coffee
# User
atom-ctags, v4.4.0
atom-handlebars, v1.2.0
atom-jade, v0.3.0
atom-ternjs, v0.8.4
autocomplete-modules, v1.3.1
autocomplete-paths, v1.0.2
bezier-curve-editor, v0.7.2
color-picker, v2.0.13
docblockr, v0.7.3
file-types, v0.5.1
fold-functions, v0.4.3
git-log, v0.4.1
hashrocket, v0.4.8
highlight-selected, v0.10.1
imdone-atom, v1.1.53
javascript-snippets, v1.0.0
kingfisher-syntax, v0.1.9
language-ejs, v0.2.0
language-liquid, v0.4.0
language-scala, v1.1.4
linter, v1.10.0
linter-clojure, v1.0.0
linter-coffeelint, v1.1.2
linter-csslint, v1.1.0
linter-eslint, v4.0.0
linter-handlebars, v2.2.0
linter-jade, v0.3.2
linter-jshint, v1.2.1
linter-jsonlint, v1.0.1
linter-scalac, v1.1.0
linter-scss-lint, v2.4.0
minimap, v4.16.0
minimap-pigments, v0.1.7
pigments, v0.18.1
pretty-json, v0.4.1
project-manager, v2.6.5
raml, v0.2.0
seti-ui, v0.8.1
symbols-tree-view, v0.10.1
toggle-invisibles, v0.1.0
trailing-spaces, v0.3.2
wakatime, v5.0.0

# Dev
No dev packages
```

**Comment by lee-dohm** [comment]
As it states in the README:

> Since the functionality provided by this package is now available in Atom proper, I have unpublished it. I'm leaving it publicly available as an example of a simple package.

**Comment by benadamstyles** [comment]
Whoops, sorry. Thanks!
